use test;
show tables;
select * from test;
insert into test values (1,2,3);
select * from test;
insert into test values (2,2,3);
select * from test;
update test set attr0=3,attr1=3 where attr0=1;
select * from test;
delete from test where attr1=3;
select * from test;
